//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SentimentModel.mbconfig.Properties {
    using System;
    using System.Diagnostics;
    using System.Globalization;
    using System.Resources;
    using static Microsoft.ML.Transforms.Text.StopWordsRemovingEstimator;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [DebuggerDisplay("{" + nameof(GetDebuggerDisplay) + "(),nq}")]
    internal class Resources : Resourceextension
    {
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        internal override string GetGetyelp_labelled_() => throw new NotImplementedException();

		/// <summary>
		///   Looks up a localized string similar to Hej Samir,
		///
		///Jag har mycket att ber??tta f??r dig ang??ende hur sommaren har varit,
		///jag har lyckats justera/navigera/orientera/systemhantera tillr??ckligt v??l
		///f??r att inte bli inlagd. Och hur jag har g??tt till v??ga ska jag klarg??ra n??r vi ses.
		///
		///F??r saken ??r den att jag kommer *aldrig* l??ta mig sj??lv bli inlagd igen, f??r det ??r *inte*
		///n??dv??ndigt. det kommer bara ske om alla kontakter jag har, inte ??r riktiga relationer, det g??ller
		///??ven formella sammanhang som relationen l??kare/patien [rest of string was truncated]&quot;;.
		/// </summary>
		internal string Getyelp_labelled_() => ResourceManager.GetString(name: "yelp_labelled_";


        private string GetDebuggerDisplay()
        {
            return ToString();
        }
    }

    internal class Resourceextension
    {
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SentimentModel.mbconfig.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow... Loved this place.	1
        ///Crust is not good.	0
        ///Not tasty and the texture was just nasty.	0
        ///Stopped by during the late May bank holiday off Rick Steve recommendation and loved it.	1
        ///The selection on the menu was great and so were the prices.	1
        ///Now I am getting angry and I want my damn pho.	0
        ///Honeslty it didn&apos;t taste THAT fresh.)	0
        ///The potatoes were like rubber and you could tell they had been made up ahead of time being kept under a warmer.	0
        ///The fries were great too.	1
        ///A great touch.	1
        ///Service was very pro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string yelp_labelled {
            get {
                return ResourceManager.GetString("yelp_labelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hej Samir,
        ///
        ///Jag har mycket att berätta för dig angående hur sommaren har varit,
        ///jag har lyckats justera/navigera/orientera/systemhantera tillräckligt väl
        ///för att inte bli inlagd. Och hur jag har gått till väga ska jag klargöra när vi ses.
        ///
        ///För saken är den att jag kommer *aldrig* låta mig själv bli inlagd igen, för det är *inte*
        ///nödvändigt. det kommer bara ske om alla kontakter jag har, inte är riktiga relationer, det gäller
        ///även formella sammanhang som relationen läkare/patient.
        ///
        ///Det här låter dr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string yelp_labelled_ {
            get {
                return ResourceManager.GetString("yelp_labelled_", resourceCulture);
            }
        }
    }
}
