//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace SentimentModel.mbconfig.Properties
{
    [CompilerGenerated, DebuggerDisplay("{GetDebuggerDisplay(),nq}"), DebuggerNonUserCode, GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    internal class Swedish
    {

        public CultureInfo Swedish { get; private set; }
        public CultureInfo Language { get; private set; }

        public override bool Equals(object obj)
        {
            return obj is Resources resources &&
                   base.Equals(obj) &&
                   Getyelp_labelled_() == resources.Getyelp_labelled_();
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(Getyelp_labelled_());
        }
    }
}